torchrun \
    --standalone \
    --nproc_per_node=4 \
    run.py \
    --task_name ssl \
    --model BIOT \
    --learning_rate 2e-3 \
    --normalize \
    --patience 0 \
    --num_epochs 100 \
    --e_layers 2 \
    --d_model 256 \
    --mask_ratio 0.3 \
    --activation "gelu" \
    --train_batch_size 1 \
    --test_batch_size 1 \
    --dropout 0.3 \
    --linear_dropout 0.5 \
    --dataset TUAB \
    --root_path <root_path> \
    --log_dir <log_dir> \
    --num_workers 8 \
    --use_scheduler \
    --warmup_epochs 20 