torchrun \
    --standalone \
    --nproc_per_node=4 \
    run.py \
    --task_name anomaly_detection \
    --model DCRNN \
    --graph_type distance \
    --normalize \
    --use_fft \
    --learning_rate 1e-3 \
    --train_batch_size 128 \
    --test_batch_size 128 \
    --data_augment \
    --patience 0 \
    --dropout 0.2 \
    --use_scheduler \
    --weight_decay 1e-4 \
    --num_workers 10 \
    --num_epochs 60 \
    --dataset TUAB \
    --root_path <root_path> \
    --log_dir <log_dir> \
    --pretrained_path <pretrained_path>